spring:
  profiles:
    active: 
    - dev
---
spring:
  profiles: dev
  application:
    name: microservicespringcloud-config-dev
---
spring:
  profiles: test
  application:
    name: microservicespringcloud-config-test
#保存为utf-8格式